dxvk.hud = fps,frametimes,memory,gpuload,version,compiler
dxvk.enableAsync = true
dxvk.numCompilerThreads = 8
d3d9.maxAvailableMemory = 4096
d3d9.deferSurfaceCreation = True
dxvk.useEarlyDiscard = True
